services:
  api:
    build:
      context: .
      dockerfile: dockerfile.backend
    image: react-flask-app-backend
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: react-flask-app-client
    ports:
      - "3000:80"